/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** 图片解密结果 */
export interface ImageDecryptResult {
  success: boolean
  outputPath?: string
  format: string
  error?: string
  isThumbnail: boolean
}
/**
 * 解密数据（直接操作字节）
 * 支持 DAT v1 (纯XOR) 和 DAT v2 (AES+XOR)
 */
export declare function decryptImageData(data: Buffer, xorKey?: Buffer | undefined | null, aesKey?: Buffer | undefined | null): Buffer
/** 密钥信息 */
export interface KeyInfo {
  wxid: string
  aesKey?: string
  xorKey?: Array<number>
  accountPath: string
}
/** 生成图片 XOR 密钥（基于 MD5） */
export declare function generateImageXorKey(md5: string): Array<number>
/** 密钥派生 - 从密码派生数据库密钥 */
export declare function deriveDbKey(password: string, salt?: Array<number> | undefined | null): Array<number>
/** 会话/聊天对象 */
export interface Session {
  id: string
  nickname?: string
  remark?: string
  type: number
  messageCount: number
}
/** 聊天消息 */
export interface Message {
  id: number
  localId: number
  serverId?: string
  createTime: number
  type: number
  subType: number
  isSender: boolean
  talker: string
  content?: string
  imagePath?: string
  voicePath?: string
  videoPath?: string
  filePath?: string
  status: number
  msgSeq: number
  displayName?: string
  groupNickname?: string
  avatarUrl?: string
  replyToId?: number
  replyToContent?: string
}
/** 联系人 */
export interface Contact {
  username: string
  alias?: string
  nickname?: string
  remark?: string
  avatar?: string
  type: number
  verifyFlag: number
  reserved1?: string
  reserved2?: string
}
/** 群聊信息 */
export interface ChatRoom {
  roomId: string
  roomOwner?: string
  memberList: Array<string>
  displayName?: string
  memberCount: number
}
/** 群成员 */
export interface GroupMember {
  username: string
  nickname?: string
  displayName?: string
}
/** 朋友圈消息 */
export interface SnsPost {
  id: number
  createTime: number
  content?: string
  images: Array<string>
  likes: Array<SnsLike>
  comments: Array<SnsComment>
}
/** 朋友圈点赞 */
export interface SnsLike {
  username: string
  nickname?: string
  createTime: number
}
/** 朋友圈评论 */
export interface SnsComment {
  id: number
  username: string
  nickname?: string
  content: string
  replyTo?: string
  createTime: number
}
/** 消息统计 */
export interface MessageStats {
  totalMessages: number
  totalChars: number
  imageCount: number
  voiceCount: number
  videoCount: number
  fileCount: number
  firstMessageTime?: number
  lastMessageTime?: number
}
/** 年度统计 */
export interface YearlyStats {
  year: number
  messageCount: number
  wordCount: number
  topSessions: Array<SessionStat>
  topWords: Array<WordStat>
  activeHours: Array<number>
  activeDays: Array<number>
}
/** 会话统计 */
export interface SessionStat {
  sessionId: string
  sessionName: string
  messageCount: number
  wordCount: number
}
/** 词频统计 */
export interface WordStat {
  word: string
  count: number
}
/** 数据库表信息 */
export interface TableInfo {
  name: string
  rowCount: number
  columns: Array<ColumnInfo>
}
/** 列信息 */
export interface ColumnInfo {
  name: string
  type: string
  notNull: boolean
  defaultValue?: string
}
/** 导出进度 */
export interface ExportProgress {
  total: number
  current: number
  percentage: number
  currentItem?: string
  stage: string
  error?: string
}
/** 数据库配置 */
export interface DbConfig {
  dbPath: string
  key?: string
  readOnly: boolean
}
/** 数据库实用函数 */
export declare function sanitizeTableName(name: string): string
/** 导出格式 */
export const enum ExportFormat {
  Html = 0,
  Json = 1,
  Csv = 2,
  Excel = 3,
  Txt = 4,
  ChatLab = 5
}
/** 导出配置 */
export interface ExportConfig {
  format: ExportFormat
  outputPath: string
  includeMedia: boolean
  includeAvatar: boolean
  dateRangeStart?: number
  dateRangeEnd?: number
  maxFileSizeMb?: number
  namingMode: string
}
/** 消息统计结果 */
export interface MessageStatsResult {
  totalMessages: number
  totalChars: number
  imageCount: number
  voiceCount: number
  videoCount: number
  fileCount: number
  firstMessageTime?: number
  lastMessageTime?: number
  messageTypeDistribution: Record<string, number>
}
/** 年度报告 */
export interface YearlyReport {
  year: number
  totalMessages: number
  totalWords: number
  topSessionsJson: string
  topWordsJson: string
  activeHoursJson: string
  activeWeekdaysJson: string
  monthlyDistributionJson: string
  highlightsJson: string
}
/** 月度统计 */
export interface MonthStat {
  month: number
  messageCount: number
  wordCount: number
}
/** 年度亮点 */
export interface Highlight {
  title: string
  description: string
  value?: string
}
/** 双人报告 */
export interface DualReport {
  withWhom: string
  firstChatDate?: string
  totalDays: number
  totalMessages: number
  myMessageCount: number
  otherMessageCount: number
  myWordCount: number
  otherWordCount: number
  myTopWords: Array<string>
  otherTopWords: Array<string>
  commonTopics: Array<string>
  specialDates: Array<SpecialDate>
  chatPatterns: ChatPatterns
}
/** 特殊日期 */
export interface SpecialDate {
  date: string
  description: string
  messageCount: number
}
/** 聊天模式 */
export interface ChatPatterns {
  whoStartsMore: string
  avgReplyTimeSeconds: number
  longestConversationMessages: number
  longestGapDays: number
}
/** 库版本信息 */
export declare function version(): string
/** 初始化日志系统 */
export declare function initLogging(): void
/** 健康检查 */
export declare function healthCheck(): Promise<boolean>
/** 获取系统信息 */
export interface SystemInfo {
  version: string
  rustVersion: string
  target: string
}
export declare function getSystemInfo(): SystemInfo
/** 图片解密服务 */
export declare class ImageDecryptService {
  constructor()
  /** 设置 XOR 密钥 */
  setXorKey(key: Array<number>): void
  /** 设置 AES 密钥 */
  setAesKey(key: string): void
  /** 解密单个 .dat 文件 */
  decryptFile(inputPath: string, outputDir: string): Promise<ImageDecryptResult>
  /** 批量解密 */
  decryptBatch(inputPaths: Array<string>, outputDir: string, concurrency: number): Promise<Array<ImageDecryptResult>>
  /** 尝试自动识别密钥 */
  tryDetectKey(samplePath: string): Array<number> | null
}
/** 密钥管理服务 */
export declare class KeyService {
  constructor()
  /**
   * 获取 macOS 微信密钥
   * 注意：这需要管理员权限，实际实现可能需要调用系统 API 或外部脚本
   */
  getMacosKey(accountPath: string): Promise<string | null>
  /** 验证密钥是否有效 */
  validateKey(key: string, sampleData: Buffer): boolean
  /** 从微信进程内存中提取密钥（仅 macOS，需要管理员权限） */
  extractFromMemory(): Promise<string | null>
  /** 从环境变量或配置文件读取密钥 */
  readFromConfig(configPath: string): KeyInfo | null
}
/** WCDB 数据库服务 */
export declare class WcdbService {
  constructor()
  /** 初始化数据库连接 */
  initialize(config: DbConfig): void
  /** 打开账户数据库 */
  openAccount(wxid: string, accountPath: string): boolean
  /** 关闭账户连接 */
  closeAccount(wxid: string): boolean
  /** 执行查询 */
  query(wxid: string, sql: string): Array<string>
  /** 获取会话列表 */
  getSessions(wxid: string): string
  /** 获取消息数量 */
  getMessageCount(wxid: string, sessionId: string): number
}
/** 导出任务控制 */
export declare class ExportTask {
  constructor(id: string, config: ExportConfig)
  /** 获取当前进度 */
  getProgress(): ExportProgress
  /** 执行导出 */
  execute(messages: Array<Message>, session: Session): Promise<boolean>
  /** 取消导出 */
  cancel(): void
  /** 暂停导出 */
  pause(): void
  /** 恢复导出 */
  resume(): void
}
/** 批量导出服务 */
export declare class ExportService {
  constructor()
  /** 创建导出任务 */
  createTask(id: string, config: ExportConfig): ExportTask
  /** 执行任务导出 */
  runTask(taskId: string, messages: Array<Message>, session: Session): Promise<boolean>
  /** 获取任务进度 */
  getTaskProgress(taskId: string): ExportProgress | null
  /** 取消任务 */
  cancelTask(taskId: string): void
  /** 清理已完成任务 */
  cleanupTasks(): number
}
/** 分析服务 */
export declare class AnalyticsService {
  constructor()
  /** 计算消息统计 */
  calculateMessageStats(messagesJson: string): MessageStatsResult
  /** 计算词频 */
  calculateWordFrequency(messagesJson: string, topN: number): string
  /** 计算活跃时间段 */
  calculateActiveHours(messagesJson: string): string
  /** 生成年度报告 */
  generateYearlyReport(messagesJson: string, year: number): YearlyReport
  /** 生成双人报告 */
  generateDualReport(messagesJson: string, sessionName: string): DualReport
  /** 清空缓存 */
  clearCache(): number
}
